### ISSUE TITLE
different ouput after 2nd execution

### ISSUE THREAD

**Issue by jackyohh** [souch/opsi-misc#1]
getting different output after executing "opsi-pkg --list --host-group pcs --ping" twice in a row.

> clientdirectory         root of directory
> 
> room1
>                         lzp01                           192.168.15.103 on    2019-04-15 21:33:24   1  d    2c:41:38:8d:ff:16
>                         lzp02                           192.168.15.104 on    2019-04-15 21:33:26   1  d    2c:41:38:8d:fe:9d
> 
> r113
>                         r113-nb01                       192.168.15.100 **off**   2019-04-15 21:33:48   1  d    38:af:d7:38:6c:f3
>                         r113-nb02                       192.168.15.101 off   2019-04-15 21:33:43   1  d    38:af:d7:38:69:65
>                         r113-nb03                       192.168.15.102 off   2019-04-15 21:33:42   1  d    38:af:d7:38:6d:b6

and after 2nd execution i get

> clientdirectory         root of directory
> 
> room1
>                         lzp01                           192.168.15.103 on    2019-04-15 21:33:24   1  d    2c:41:38:8d:ff:16
>                         lzp02                           192.168.15.104 on    2019-04-15 21:33:26   1  d    2c:41:38:8d:fe:9d
> 
> r113
>                         r113-nb01                       192.168.15.100 **on**    2019-04-15 21:33:48   1  d    38:af:d7:38:6c:f3
>                         r113-nb02                       192.168.15.101 off   2019-04-15 21:33:43   1  d    38:af:d7:38:69:65
>                         r113-nb03                       192.168.15.102 off   2019-04-15 21:33:42   1  d    38:af:d7:38:6d:b6

r113-nb01 is turned off but after 2nd execution it is shown as turned on. i marked it bold in quotes.

**Comment by souch** [comment]
Ouch, it has been a long time I have not stick my nose into this code. I do not use anymore opsi-misc and I have not the environment to fix it.

Sorry, I cannot fix any issue.
